name: shelf_rate_limiter
description: Limit requests to your shelf backend server.
repository: https://github.com/ramyak-mehra/shelf_rate_limiter
version: 1.0.0
environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  shelf: ^1.2.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
